osx_image: xcode9.2
language: objective-c

env:
  global:
  - WORKSPACE=Image360.xcworkspace
  - Image360_SCHEME="Image360"
  - IOS_EXAMPLE_SCHEME="iOS Example"
  matrix:
  - DESTINATION="OS=11.1,name=iPhone X"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks

# Build Framework in Debug
- xcodebuild -workspace "$WORKSPACE" -scheme "$Image360_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;

# Build Framework in Release
- xcodebuild -workspace "$WORKSPACE" -scheme "$Image360_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;

# Build an example project
- xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
